version: '3'

volumes:
  postgres_data:
    driver: local

services:

#  postgres:
#    image: postgres:14.4-alpine
#    volumes:
#      - postgres_data:/var/lib/postgresql/data
#    environment:
#      POSTGRES_DB: spring_homework2
#      POSTGRES_USER: postgres
#      POSTGRES_PASSWORD: password
#    ports:
#      - "5436:5432"
  category-service:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: todo-homework
    ports:
      - "8989:8080"